### ISSUE TITLE
[TODO] 待完善功能

### ISSUE THREAD

**Issue by Chanyon** [fzdwx/popup-translation#17]
### TODO
- [x] add setting page (#16)
- [ ] 完善`模式二`翻译逻辑
- [x] local save key (key.json)  (https://github.com/fzdwx/popup-translation/commit/c2b7e3e6fc33a613fdee80d88a7116f8a6fc501a)
- [x] get local key (https://github.com/fzdwx/popup-translation/commit/c2b7e3e6fc33a613fdee80d88a7116f8a6fc501a)
- [x] 组件优化 (#18)
- [ ] 模式2 显示时，输入框 focus
- [ ] 模式2 快捷键翻译, 当处在模式2时，在输入框可以有快捷键响应并调用翻译
- [x] 添加翻译语言选项, 现在只能由 英文 到 中文

**Comment by fzdwx** [comment]
我把 mode1 也就是聚合翻译拆出来了，然后感觉可以把 `Nav` 加个 solt ，两个 mode 都往里面加按钮

**Comment by fzdwx** [comment]
配置我修改成了从 ts 调用 rust,不直接调用 tauri 的 api

**Comment by fzdwx** [comment]
![image](https://user-images.githubusercontent.com/65269574/224993326-8e358db0-3a73-41f8-88e7-28564d15380f.png)


你的上面有这个吗？ 这个会导致打不了包

**Comment by Chanyon** [comment]
> ![image](https://user-images.githubusercontent.com/65269574/224993326-8e358db0-3a73-41f8-88e7-28564d15380f.png)
> 
> 你的上面有这个吗？ 这个会导致打不了包

改这样：
```
const emit = defineEmits(["update:modelValue"]);
const inputValue = function (e: any) {
  emit("update:modelValue", e.target.value);
}
</script>
<template>
  <div class="ipt">
    <label for="ipt"> {{ props.platform }}: </label>
    <input type="text" name="ipt" id="ipt" :value="modelValue" @input="inputValue($event)" />
  </div>
</template>
```

**Comment by fzdwx** [comment]
> > ![image](https://user-images.githubusercontent.com/65269574/224993326-8e358db0-3a73-41f8-88e7-28564d15380f.png)
> > 你的上面有这个吗？ 这个会导致打不了包
> 
> 改这样：
> 
> ```
> const emit = defineEmits(["update:modelValue"]);
> const inputValue = function (e: any) {
>   emit("update:modelValue", e.target.value);
> }
> </script>
> <template>
>   <div class="ipt">
>     <label for="ipt"> {{ props.platform }}: </label>
>     <input type="text" name="ipt" id="ipt" :value="modelValue" @input="inputValue($event)" />
>   </div>
> </template>
> ```

我发现改了之后，input 坏了，没有绑定了

**Comment by fzdwx** [comment]
日志里面的值没有变

![录屏_选择区域_20230314221126](https://user-images.githubusercontent.com/65269574/225028217-ffcc1c7e-2dc0-48a2-8b32-bda66bd90f4b.gif)

**Comment by Chanyon** [comment]
删掉这试一下
![image](https://user-images.githubusercontent.com/40350332/225028837-f3a60083-5c85-4cdf-946c-5f1e0d250dd9.png)

**Comment by fzdwx** [comment]
不是，都不回显数据了

这个是以前的


![image](https://user-images.githubusercontent.com/65269574/225029625-7dfc0e7c-2f93-43d3-8793-be6e660b3d72.png)

**Comment by fzdwx** [comment]
OK，好了 。 我的, 不好意思


这个命名必须是 `modelValue` 吗？我改成了 ` modeValue` 就坏了

**Comment by Chanyon** [comment]
> OK，好了 。 我的
> 
> 这个命名必须是 `modelValue` 吗？我改成了 ` modeValue` 就坏了

这个是默认命名，可以改的，比如这样
```
<MyComponent v-model:title="bookTitle" />
<!-- MyComponent.vue -->
<script setup>
defineProps(['title'])
defineEmits(['update:title'])
</script>
<template>
  <input
    type="text"
    :value="title"
    @input="$emit('update:title', $event.target.value)"
  />
</template>
```

**Comment by fzdwx** [comment]
我昨天加的快捷键的配置有点问题，就是点保存后没有效果，tauri 给报错了，但是重启后就会生效

**Comment by Chanyon** [comment]
> 我昨天加的快捷键的配置有点问题，就是点保存后没有效果，tauri 给报错了，但是重启后就会生效

我目前没有解决tauri窗口不显示的问题，所以用不了tauri后端功能。
我明天下载zip文件重新编译，再看能不能运行？

**Comment by Chanyon** [comment]
> 我昨天加的快捷键的配置有点问题，就是点保存后没有效果，tauri 给报错了，但是重启后就会生效

如果保存后能自动重启应用是否能修复？

**Comment by fzdwx** [comment]
> > 我昨天加的快捷键的配置有点问题，就是点保存后没有效果，tauri 给报错了，但是重启后就会生效
> 
> 如果保存后能自动重启应用是否能修复？

可以试试这个，明天我release一下，然后你在下

**Comment by Chanyon** [comment]
我一直认为应用启动时窗口会自动显示一次？原来要使用快捷键才显示。
![image](https://user-images.githubusercontent.com/40350332/226968036-c0125d0d-e4af-4ac2-b73f-e7528e64bfc8.png)

**Comment by fzdwx** [comment]
... 是的

---

现在改成第一次显示了, 你的可以用了吗？

**Comment by Chanyon** [comment]
> ... 是的
> 
> 现在改成第一次显示了, 你的可以用了吗？

可以

**Comment by fzdwx** [comment]
快捷键修改可以了，我以前是直接取消所有注册的，改成了判断后在注销。


https://github.com/fzdwx/popup-translation/commit/4c2414bc991790910c61975fd858e90c6d6055a8#diff-621c943cc5c51fe96e801e2019794959b5d6f7fad1e394cd14ef9ad7c3212273L132

**Comment by fzdwx** [comment]
我把 mian window 的文件都移动一下，后面可以把 设置 开一个单独的窗口来

大概思路是

1. 在 root 路径创建 setting.html
2. 在 src/setting/ 里面写 js

不知道这样行不行


https://github.com/fzdwx/popup-translation/commit/49507350a3e00d44970d8525e14762131239ee1d

**Comment by Chanyon** [comment]
> 我把 mian window 的文件都移动一下，后面可以把 设置 开一个单独的窗口来
> 
> 大概思路是
> 
> 1. 在 root 路径创建 setting.html
> 2. 在 src/setting/ 里面写 js
> 
> 不知道这样行不行
> 
> [4950735](https://github.com/fzdwx/popup-translation/commit/49507350a3e00d44970d8525e14762131239ee1d)

看文法档是可以的`https://tauri.app/zh-cn/v1/guides/features/multiwindow`

**Comment by fzdwx** [comment]
我刚刚加了个语言切换的功能， 但是有一个问题, 有道的 api 是不支持指定 target lang 吗？

**Comment by fzdwx** [comment]
有道这个 api 可能还有点问题，翻译的内容不全：

![image](https://user-images.githubusercontent.com/65269574/228561367-679c0106-d832-44ea-aa13-e44716849119.png)


![image](https://user-images.githubusercontent.com/65269574/228561411-a224f1d7-654b-4517-8b53-10dd6bff9a8e.png)

**Comment by Chanyon** [comment]
`我刚刚加了个语言切换的功能， 但是有一个问题, 有道的 api 是不支持指定 target lang 吗？`
`有道这个 api 可能还有点问题，翻译的内容不全`:

这个free api，翻译的长度有限，支持翻译选项很少！删除youdao?

**Comment by fzdwx** [comment]
我也找了一下，没有什么能用的，不过可以考虑接入官方的
